"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { KeyRound, Mail } from "lucide-react";
import { Button } from "@/components/ui/button";
import { createClient } from "@/lib/supabase/client";

const configured=Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
export function LoginForm(){const router=useRouter();const[email,setEmail]=useState(""),[otp,setOtp]=useState(""),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[cooldown,setCooldown]=useState(0);
useEffect(()=>{if(!cooldown)return;const timer=setInterval(()=>setCooldown(x=>Math.max(0,x-1)),1000);return()=>clearInterval(timer)},[cooldown]);
async function send(){setBusy(true);setError("");try{if(!configured){setSent(true);setCooldown(30);return}const{error}=await createClient().auth.signInWithOtp({email,options:{shouldCreateUser:false}});if(error)throw error;setSent(true);setCooldown(60)}catch(e){setError(e instanceof Error?e.message:"Could not send the OTP.")}finally{setBusy(false)}}
async function verify(){setBusy(true);setError("");try{if(!configured){router.push("/student");return}const{error}=await createClient().auth.verifyOtp({email,token:otp,type:"email"});if(error)throw error;router.replace("/student");router.refresh()}catch(e){setError(e instanceof Error?e.message:"The code is invalid or expired.")}finally{setBusy(false)}}
return <form className="mt-8 space-y-5" onSubmit={e=>{e.preventDefault();void(sent?verify():send())}}><label className="block text-sm font-bold">Email address<span className="relative mt-2 block"><Mail className="absolute left-4 top-3.5 text-muted" size={18}/><input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} disabled={sent} placeholder="student@example.com" className="h-12 w-full rounded-xl border border-line bg-white pl-11 pr-4 text-sm transition focus:border-deep-blue disabled:bg-slate-50"/></span></label>{sent&&<label className="block text-sm font-bold">One-time code<span className="relative mt-2 block"><KeyRound className="absolute left-4 top-3.5 text-muted" size={18}/><input required inputMode="numeric" autoComplete="one-time-code" minLength={6} maxLength={8} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,""))} placeholder="Enter the code from your email" className="h-12 w-full rounded-xl border border-line bg-white pl-11 pr-4 text-sm tracking-[.25em] transition focus:border-deep-blue"/></span></label>}{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}{!configured&&<p className="rounded-lg bg-amber-50 p-3 text-xs text-amber-900">Development mode: Supabase is not configured. Submit any valid email and code to enter the existing demo portal.</p>}<Button disabled={busy} type="submit" className="w-full">{busy?"Please wait…":sent?"Verify & sign in":"Email me a code"}</Button>{sent&&<div className="flex items-center justify-between text-sm"><button type="button" className="font-semibold text-brand" onClick={()=>{setSent(false);setOtp("");setError("")}}>Change email</button><button type="button" disabled={cooldown>0||busy} onClick={()=>void send()} className="font-semibold text-brand disabled:text-muted">{cooldown?`Resend in ${cooldown}s`:"Resend code"}</button></div>}<p className="text-center text-sm text-muted">New to ALS? <Link href="/#courses" className="font-bold text-brand">Contact admissions</Link></p></form>}
