"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Option={id:string;content:string}; type Question={id:string;prompt:string;type:string;question_options:Option[]}; type TestQuestion={display_order:number;questions:Question};
type Attempt={id:string;status:string;score:number|null;started_at:string;expires_at:string|null;question_order:string[];option_order:Record<string,string[]>;correct_count:number|null;incorrect_count:number|null;unanswered_count:number|null;negative_marks_total:number|null;attempt_answers?:{question_id:string;selected_option_ids:string[]}[]};
type Data={user:{id:string};test:{id:string;title:string;duration_minutes:number;max_attempts:number|null;randomize_questions:boolean;show_results:boolean;test_questions:TestQuestion[]};attempts:Attempt[]};
type Review={score:number;correct:number;incorrect:number;unanswered:number;negative_marks:number;answers:{question_id:string;prompt:string;selected_option_ids:string[];correct_option_ids:string[];is_correct:boolean|null;marks_awarded:number|null;explanation:string|null}[]};
const formatTime=(seconds:number)=>`${Math.floor(seconds/60).toString().padStart(2,"0")}:${(seconds%60).toString().padStart(2,"0")}`;
export function BackendTestEngine({data}:{data:Data}){
  const currentAttempt=data.attempts.find(x=>x.status==="in_progress"),completed=data.attempts.find(x=>x.status!=="in_progress");
  const [attempt,setAttempt]=useState<Attempt|null>(currentAttempt||null),[index,setIndex]=useState(0),[answers,setAnswers]=useState<Record<string,string[]>>(()=>Object.fromEntries((currentAttempt?.attempt_answers||[]).map(x=>[x.question_id,x.selected_option_ids]))),[review,setReview]=useState<Review|null>(null),[remaining,setRemaining]=useState(0),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const questions=useMemo(()=>{const base=[...data.test.test_questions].sort((a,b)=>a.display_order-b.display_order);if(!attempt?.question_order?.length)return base;const byId=new Map(base.map(x=>[x.questions.id,x]));return attempt.question_order.map(id=>byId.get(id)).filter((x):x is TestQuestion=>Boolean(x))},[data.test.test_questions,attempt]);
  async function loadReview(attemptId:string){const{data:value,error:e}=await createClient().rpc("get_test_review",{target_attempt:attemptId});if(e)setError(e.message);else setReview(value as Review|null)}
  async function submit(attemptId=attempt?.id){if(!attemptId||busy)return;setBusy(true);const{error:e}=await createClient().rpc("submit_test_attempt",{target_attempt:attemptId});if(e)setError(e.message);else await loadReview(attemptId);setBusy(false)}
  // The review is intentionally fetched only after hydration so protected answer
  // data never becomes part of the pre-submission test payload.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{if(completed)void loadReview(completed.id)},[]);// eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(!attempt?.expires_at)return;const tick=()=>{const left=Math.max(0,Math.ceil((new Date(attempt.expires_at!).getTime()-Date.now())/1000));setRemaining(left);if(left===0)void submit(attempt.id)};tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer)},[attempt?.id,attempt?.expires_at]);// eslint-disable-line react-hooks/exhaustive-deps
  async function start(){setBusy(true);setError("");const{data:row,error:e}=await createClient().rpc("start_test_attempt",{target_test:data.test.id});if(e)setError(e.message);else setAttempt(row as Attempt);setBusy(false)}
  async function choose(question:string,option:string,type:string){if(!attempt||remaining===0)return;const previous=answers[question]||[];const selected=type==="multiple_mcq"?previous.includes(option)?previous.filter(x=>x!==option):[...previous,option]:[option];setAnswers(v=>({...v,[question]:selected}));const{error:e}=await createClient().rpc("save_attempt_answer",{target_attempt:attempt.id,target_question:question,option_ids:selected});if(e){setError(e.message);setAnswers(v=>({...v,[question]:previous}))}}
  if(review)return <section className="card mx-auto max-w-3xl p-6 sm:p-8"><p className="text-sm font-bold uppercase text-muted">Submitted result</p><h1 className="mt-2 text-3xl font-bold">{data.test.title}</h1><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-5">{[["Score",review.score],["Correct",review.correct],["Incorrect",review.incorrect],["Unanswered",review.unanswered],["Negative",review.negative_marks]].map(([label,value])=><div className="rounded border p-3" key={label}><strong className="text-2xl text-brand">{value}</strong><p className="text-xs text-muted">{label}</p></div>)}</div>{review.answers.length>0&&<div className="mt-6 space-y-4">{review.answers.map((answer,i)=><article className="rounded border p-4" key={answer.question_id}><p className="text-xs font-bold text-muted">Question {i+1}</p><h2 className="mt-1 font-bold">{answer.prompt}</h2><p className={`mt-2 text-sm font-bold ${answer.is_correct?"text-green-700":"text-red-700"}`}>{answer.is_correct?"Correct":"Incorrect or unanswered"} · {answer.marks_awarded??0} marks</p>{answer.explanation&&<p className="mt-2 text-sm text-muted">{answer.explanation}</p>}</article>)}</div>}</section>;
  if(!attempt)return <section className="card mx-auto max-w-2xl p-8"><h1 className="text-3xl font-bold">{data.test.title}</h1><p className="mt-3 text-muted">{questions.length} questions · {data.test.duration_minutes} minutes</p>{error&&<p className="mt-3 text-red-700">{error}</p>}<button disabled={busy} onClick={()=>void start()} className="mt-6 rounded bg-brand px-5 py-3 font-bold text-white disabled:opacity-50">Start attempt</button></section>;
  const current=questions[index]?.questions;if(!current)return <p>No questions are assigned to this test.</p>;const optionOrder=attempt.option_order?.[current.id]||[];current.question_options.sort((a,b)=>(optionOrder.indexOf(a.id)<0?999:optionOrder.indexOf(a.id))-(optionOrder.indexOf(b.id)<0?999:optionOrder.indexOf(b.id)));
  return <div className="mx-auto max-w-3xl"><header className="mb-5 flex flex-wrap justify-between gap-3"><h1 className="text-xl font-bold">{data.test.title}</h1><div className="flex gap-4"><span>Question {index+1} of {questions.length}</span><strong className={remaining<60?"text-red-700":"text-brand"}>{formatTime(remaining)}</strong></div></header><section className="card p-6"><h2 className="text-xl font-bold">{current.prompt}</h2><div className="mt-5 space-y-3">{current.question_options.map(option=><label key={option.id} className="flex gap-3 rounded border p-4"><input type={current.type==="multiple_mcq"?"checkbox":"radio"} name={current.id} checked={(answers[current.id]||[]).includes(option.id)} onChange={()=>void choose(current.id,option.id,current.type)}/>{option.content}</label>)}</div>{error&&<p className="mt-3 text-red-700">{error}</p>}<div className="mt-6 flex justify-between"><button disabled={!index||busy} onClick={()=>setIndex(x=>x-1)} className="rounded border px-4 py-2">Previous</button>{index<questions.length-1?<button disabled={busy} onClick={()=>setIndex(x=>x+1)} className="rounded bg-brand px-4 py-2 text-white">Next</button>:<button disabled={busy} onClick={()=>void submit()} className="rounded bg-brand px-4 py-2 font-bold text-white disabled:opacity-50">Submit test</button>}</div></section></div>;
}
