import type{AdminStudent,AdminTeacher,AuditEvent,Batch,Certificate,CmsSection,Payment,SupportTicket}from"@/types/admin";
export const adminStudents:AdminStudent[]=[{id:"ameen-mohammed",name:"Ameen Mohammed",email:"ameen@example.com",courses:3,progress:72,lastActive:"Today",status:"Active",joined:"12 Jun 2026"},{id:"fathima-n",name:"Fathima N",email:"fathima@example.com",courses:2,progress:48,lastActive:"2 days ago",status:"Active",joined:"18 Jun 2026"},{id:"rahul-kumar",name:"Rahul Kumar",email:"rahul@example.com",courses:1,progress:21,lastActive:"9 days ago",status:"Inactive",joined:"02 Jul 2026"},{id:"mariam-ali",name:"Mariam Ali",email:"mariam@example.com",courses:2,progress:81,lastActive:"Today",status:"Pending",joined:"24 Aug 2026"}];
export const adminTeachers:AdminTeacher[]=[{id:"sarah-ahmed",name:"Dr. Sarah Ahmed",specialization:"Clinical Biochemistry",courses:3,students:284,classes:42,status:"Active",lastActive:"Today"},{id:"omar-hassan",name:"Dr. Omar Hassan",specialization:"Microbiology",courses:2,students:142,classes:31,status:"Active",lastActive:"Today"},{id:"lina-farouk",name:"Dr. Lina Farouk",specialization:"Hematology",courses:2,students:96,classes:24,status:"Pending",lastActive:"3 days ago"}];
export const batches:Batch[]=[{id:"cb-2026-a",course:"Clinical Biochemistry",teacher:"Dr. Sarah Ahmed",students:186,start:"01 Jun 2026",end:"30 Nov 2026",status:"Active"},{id:"mb-2026-a",course:"Microbiology Essentials",teacher:"Dr. Omar Hassan",students:72,start:"15 Jun 2026",end:"15 Dec 2026",status:"Active"},{id:"hm-2026-a",course:"Hematology Fundamentals",teacher:"Dr. Lina Farouk",students:54,start:"01 Sep 2026",end:"28 Feb 2027",status:"Upcoming"}];
export const payments:Payment[]=[{id:"als-pay-001284",student:"Ameen Mohammed",course:"Clinical Biochemistry",amount:450,method:"Online",status:"Paid",date:"28 Aug 2026"},{id:"als-pay-001285",student:"Fathima N",course:"Microbiology Essentials",amount:350,method:"Bank Transfer",status:"Pending",date:"28 Aug 2026"},{id:"als-pay-001286",student:"Rahul Kumar",course:"Hematology Fundamentals",amount:400,method:"Online",status:"Failed",date:"27 Aug 2026"}];
export const certificates:Certificate[]=[{id:"ALS-CERT-10021",student:"Ameen Mohammed",course:"Basic Laboratory Safety",completed:"18 Aug 2026",issued:"19 Aug 2026",status:"Issued"},{id:"ALS-CERT-10022",student:"Mariam Ali",course:"Clinical Biochemistry",completed:"27 Aug 2026",issued:"—",status:"Eligible"}];
export const auditEvents:AuditEvent[]=[{id:"e1",date:"Today • 10:42",user:"ALS Admin",action:"Created student",entity:"Ameen Mohammed",details:"Account and enrollment created"},{id:"e2",date:"Today • 09:18",user:"Dr. Sarah Ahmed",action:"Published lesson",entity:"Module 04",details:"Clinical Biochemistry"},{id:"e3",date:"Yesterday",user:"ALS Admin",action:"Marked paid",entity:"ALS-PAY-001284",details:"AED 450"}];
export const supportTickets:SupportTicket[]=[{id:"als-sup-1284",user:"Ameen Mohammed",role:"Student",topic:"Course progress not updating",priority:"High",status:"Open",created:"Today"},{id:"als-sup-1285",user:"Dr. Sarah Ahmed",role:"Teacher",topic:"Unable to attach class resource",priority:"Medium",status:"In Progress",created:"Yesterday"}];
export const cmsSections:CmsSection[]=["Hero","Metrics","Featured Courses","Learning Experience","Faculty","Testimonials","CTA"].map((name,i)=>({id:`cms-${i}`,name,visible:true}));
