import type {Assessment,Course,CourseModule,Resource} from "@/types";
export const courses:Course[]=[
{id:"cb",slug:"clinical-biochemistry",title:"Clinical Biochemistry",category:"Clinical Science",lessons:31,duration:"14 hours",difficulty:"Intermediate",instructor:"Dr. Sarah Ahmed",progress:72,status:"in-progress",description:"Build confident clinical reasoning through biomarkers, metabolism, enzymes, and diagnostic interpretation."},
{id:"me",slug:"microbiology-essentials",title:"Microbiology Essentials",category:"Microbiology",lessons:24,duration:"11 hours",difficulty:"Beginner",instructor:"Dr. Omar Hassan",progress:48,status:"in-progress",description:"Master core organisms, culture methods, identification, and infection control."},
{id:"hf",slug:"hematology-fundamentals",title:"Hematology Fundamentals",category:"Hematology",lessons:28,duration:"12 hours",difficulty:"Beginner",instructor:"Dr. Lina Farouk",progress:25,status:"in-progress",description:"Understand blood cell morphology, disorders, and essential laboratory workflows."},
{id:"mlt",slug:"medical-laboratory-technology",title:"Medical Laboratory Technology",category:"Laboratory Practice",lessons:36,duration:"18 hours",difficulty:"Intermediate",instructor:"Prof. Nadia Karim",progress:0,status:"in-progress",description:"A practical overview of modern medical laboratory systems and quality practice."},
{id:"safety",slug:"basic-laboratory-safety",title:"Basic Laboratory Safety",category:"Professional Practice",lessons:12,duration:"4 hours",difficulty:"Beginner",instructor:"Dr. Youssef Ali",progress:100,status:"completed",certificate:true,description:"Essential biosafety, risk prevention, and incident response for laboratory teams."}];
const lesson=(id:string,title:string,completed:boolean,slug="")=>({id,slug,title,duration:"18 min",completed});
export const clinicalModules:CourseModule[]=[
{id:"m1",number:"01",title:"Introduction to Clinical Biochemistry",progress:"4/4 complete",lessons:["The Clinical Laboratory","Specimen Quality","Reference Intervals","Quality Control"].map((t,i)=>lesson(`m1-${i}`,t,true))},
{id:"m2",number:"02",title:"Carbohydrate Metabolism",progress:"5/5 complete",lessons:["Glucose Homeostasis","Diabetes Mellitus","Oral Glucose Tolerance","HbA1c","Case Review"].map((t,i)=>lesson(`m2-${i}`,t,true))},
{id:"m3",number:"03",title:"Enzymes & Diagnostic Applications",progress:"3/4 complete",lessons:[lesson("l31","Introduction to Enzymes",true),lesson("l32","Enzyme Classification",true),lesson("l33","Clinical Enzymology",true),{...lesson("l34","Diagnostic Enzyme Markers",false,"diagnostic-enzyme-markers"),current:true}]},
{id:"m4",number:"04",title:"Liver Function Tests",progress:"0/5 complete",lessons:["Liver Physiology","Bilirubin","Synthetic Function","Patterns of Injury","Clinical Cases"].map((t,i)=>lesson(`m4-${i}`,t,false))}];
export const courseResources:Resource[]=[{id:"r1",title:"Clinical Biochemistry Notes.pdf",size:"4.2 MB",type:"PDF"},{id:"r2",title:"Reference Values.pdf",size:"1.1 MB",type:"PDF"},{id:"r3",title:"Enzyme Classification Chart.pdf",type:"Guide"}];
export const assessments:Assessment[]=[{id:"a1",title:"Quiz 01",status:"Completed",score:"18 / 20"},{id:"a2",title:"Quiz 02",status:"Completed",score:"17 / 20"},{id:"a3",title:"Quiz 03",status:"Available",detail:"20 Questions"},{id:"a4",title:"Final Assessment",status:"Locked"}];
