"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { ALSLogo } from "@/components/shared/als-logo";
import { Activity,Award,BarChart3,Bell,BookOpen,CalendarDays,ChevronDown,CircleDollarSign,CircleHelp,ClipboardCheck,FileBadge,GraduationCap,Grid2X2,HelpCircle,Home,Landmark,Layers3,MessageSquare,PanelsTopLeft,Plus,Search,Settings,UserRound,Users,Video,WalletCards,X } from "lucide-react";

const nav=[{h:"MAIN",items:[["/admin","Dashboard",Home],["/admin/students","Students",Users],["/admin/teachers","Teachers",UserRound],["/admin/courses","Courses",BookOpen],["/admin/batches","Batches",Layers3],["/admin/live-classes","Live Classes",CalendarDays],["/admin/assessments","Assessments",ClipboardCheck]]},{h:"OPERATIONS",items:[["/admin/payments","Payments",CircleDollarSign],["/admin/certificates","Certificates",FileBadge],["/admin/notifications","Notifications",Bell],["/admin/reports","Reports",BarChart3]]},{h:"CONTENT",items:[["/admin/announcements","Announcements",MessageSquare],["/admin/cms","Website / CMS",Landmark]]}];
const moreItems=[["/admin/teachers","Teachers",GraduationCap],["/admin/batches","Batches",Layers3],["/admin/live-classes","Live Classes",Video],["/admin/assessments","Assessments",ClipboardCheck],["/admin/certificates","Certificates",Award],["/admin/notifications","Notifications",Bell],["/admin/reports","Reports",BarChart3],["/admin/support","Support",CircleHelp],["/admin/cms","CMS",PanelsTopLeft],["/admin/settings","Settings",Settings],["/admin/profile","Profile",UserRound]] as const;
function isActive(path:string,href:string){return href==="/admin"?path===href:path.startsWith(href)}
function NLink({href,label,Icon,close}:{href:string;label:string;Icon:typeof Home;close?:()=>void}){const path=usePathname();const active=isActive(path,href);return <Link href={href} onClick={close} className={`flex min-h-10 items-center gap-3 rounded px-3 text-sm font-semibold ${active?"bg-brand/10 text-brand":"text-[#51424a] hover:bg-white"}`}><Icon size={17}/>{label}</Link>}
function MobileNavLink({href,label,Icon}:{href:string;label:string;Icon:typeof Home}){const path=usePathname();const active=isActive(path,href);return <Link href={href} aria-current={active?"page":undefined} className={`group flex min-h-16 flex-col items-center justify-center gap-1 text-[11px] font-semibold ${active?"text-brand":"text-[#625761]"}`}><span className={`grid h-7 w-10 place-items-center rounded-full transition-colors ${active?"bg-brand/10":"group-hover:bg-slate-100"}`}><Icon size={20}/></span>{label}</Link>}

export function AdminShell({children}:{children:React.ReactNode}){const[moreOpen,setMoreOpen]=useState(false);const[add,setAdd]=useState(false);const path=usePathname();return <div data-admin-shell className="min-h-screen bg-[#faf8ff] pb-[calc(4.5rem+env(safe-area-inset-bottom))] lg:pb-0">
<aside className="fixed inset-y-0 left-0 z-30 hidden w-60 overflow-y-auto border-r border-[#ead1da] bg-[#faf8ff] p-4 lg:block"><ALSLogo/><button onClick={()=>setAdd(!add)} className="mt-7 flex min-h-11 w-full items-center justify-center gap-2 rounded bg-brand text-sm font-bold text-white"><Plus/>Quick Add<ChevronDown size={16}/></button>{add&&<div className="mt-2 rounded-lg border border-[#ead1da] bg-white p-2 shadow-lg">{[["Student","/admin/students/new"],["Teacher","/admin/teachers/new"],["Course","/admin/courses/new"],["Batch","/admin/batches?create=1"],["Live Class","/admin/live-classes"],["Announcement","/admin/announcements"]].map(item=><Link key={item[0]} href={item[1]} onClick={()=>setAdd(false)} className="block rounded px-3 py-2 text-sm hover:bg-brand/10">{item[0]}</Link>)}</div>}{nav.map(group=><div className="mt-6" key={group.h}><p className="mb-2 px-3 text-[10px] font-bold tracking-[.14em] text-muted">{group.h}</p><nav className="space-y-1">{group.items.map(([href,label,Icon])=><NLink key={href as string} href={href as string} label={label as string} Icon={Icon as typeof Home}/>)}</nav></div>)}<div className="mt-6 border-t border-[#ead1da] pt-3"><NLink href="/admin/support" label="Help & Support" Icon={HelpCircle}/><NLink href="/admin/activity" label="Activity Log" Icon={Activity}/><NLink href="/admin/settings" label="Settings" Icon={Settings}/><NLink href="/admin/profile" label="Admin Profile" Icon={UserRound}/></div></aside>
<div className="lg:pl-60"><header data-admin-topbar className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-[#ead1da] bg-[#faf8ff]/90 px-4 backdrop-blur-xl sm:px-6"><strong className="text-base sm:text-lg">ALS Administration</strong><div className="flex items-center gap-1.5 sm:gap-2"><label className="relative hidden md:block"><Search className="absolute left-3 top-2.5" size={17}/><span className="sr-only">Global search</span><input className="h-10 w-72 rounded border border-[#ddbec9] bg-white pl-10 pr-3 text-sm" placeholder="Search students, teachers, courses..."/></label><button onClick={()=>setAdd(!add)} className="hidden min-h-10 items-center gap-2 rounded bg-brand px-3 text-sm font-bold text-white sm:flex"><Plus/>Add</button><Link href="/admin/notifications" aria-label="Admin notifications" className="grid h-11 w-11 place-items-center rounded-full hover:bg-white"><Bell size={19}/></Link><Link href="/admin/profile" className="grid h-10 w-10 place-items-center rounded-full bg-deep-blue text-xs font-bold text-white" aria-label="Admin profile">AA</Link></div></header><main className="mx-auto max-w-[1440px] p-4 sm:p-6 lg:p-8">{children}</main></div>
<nav aria-label="Mobile admin navigation" className="fixed inset-x-0 bottom-0 z-40 grid min-h-[4.5rem] grid-cols-5 border-t border-[#ead1da] bg-white/95 pb-[env(safe-area-inset-bottom)] shadow-[0_-6px_20px_rgba(42,67,127,.06)] backdrop-blur-xl lg:hidden"><MobileNavLink href="/admin" label="Home" Icon={Home}/><MobileNavLink href="/admin/students" label="Students" Icon={Users}/><MobileNavLink href="/admin/courses" label="Courses" Icon={BookOpen}/><MobileNavLink href="/admin/payments" label="Payments" Icon={WalletCards}/><button onClick={()=>setMoreOpen(true)} aria-expanded={moreOpen} className={`flex min-h-16 flex-col items-center justify-center gap-1 text-[11px] font-semibold ${moreOpen?"text-brand":"text-[#625761]"}`}><span className={`grid h-7 w-10 place-items-center rounded-full ${moreOpen?"bg-brand/10":""}`}><Grid2X2 size={20}/></span>More</button></nav>
{moreOpen&&<div className="fixed inset-0 z-50 bg-black/40 lg:hidden" onClick={()=>setMoreOpen(false)}><section role="dialog" aria-modal="true" aria-labelledby="admin-more-title" className="absolute inset-x-0 bottom-0 max-h-[82vh] overflow-y-auto rounded-t-2xl bg-white px-4 pb-[calc(1rem+env(safe-area-inset-bottom))] pt-4 shadow-2xl" onClick={event=>event.stopPropagation()}><div className="mx-auto mb-3 h-1 w-10 rounded-full bg-slate-200"/><div className="flex items-center justify-between"><h2 id="admin-more-title" className="text-xl font-bold">More</h2><button onClick={()=>setMoreOpen(false)} aria-label="Close more menu" className="grid h-11 w-11 place-items-center rounded-full hover:bg-slate-100"><X size={20}/></button></div><div className="mt-3 grid grid-cols-2 gap-2">{moreItems.map(([href,label,Icon])=>{const active=isActive(path,href);return <Link key={href} href={href} onClick={()=>setMoreOpen(false)} aria-current={active?"page":undefined} className={`flex min-h-12 items-center gap-3 rounded-lg px-3 text-sm font-semibold transition-colors ${active?"bg-brand/10 text-brand":"text-[#51424a] hover:bg-slate-50"}`}><Icon size={19}/>{label}</Link>})}</div></section></div>}
</div>}
