import assert from "node:assert/strict";
import {readFileSync,writeFileSync} from "node:fs";
import {login,ok,query} from "./biochemistry-client.mjs";
import {questionPayload,projectQuestion,questionSelect,identity,sourceIdentity,batch} from "./biochemistry-import-model.mjs";
const read=p=>JSON.parse(readFileSync(p,"utf8"));
const manifest=read("docs/biochemistry-import-manifest.json"),input=read(".local-qa/biochemistry-preflight-records.json"),checks=[];
const pass=(label,condition)=>{assert.ok(condition,label);checks.push(label);};
const {db:admin}=await login();const rows=[];
for(let offset=0;offset<713;offset+=100)rows.push(...ok(await admin.from("questions").select(questionSelect).like("source_label",`%batch=${batch}%`).order("id").range(offset,offset+99)));
pass("713 persisted source questions",rows.length===713);
const byId=new Map(rows.map(q=>[q.id,q]));
for(const q of input.filter(q=>q.classification!=="QUARANTINE"))assert.deepEqual(projectQuestion(byId.get(identity(sourceIdentity(q)))),questionPayload(q,manifest.taxonomy),`BIO ${q.bio} Q${q.source_sequence} payload mismatch`);
pass("Every canonical payload equals approved source: text, order, keys, marks, rich AST, source metadata",true);
pass("708 Active and five Draft",rows.filter(q=>q.status==="active").length===708&&rows.filter(q=>q.status==="draft").length===5);
const quarantine=read("docs/biochemistry-quarantine.json");assert.equal(quarantine.length,1);
const {disposition,...raw}=quarantine[0];assert.ok(disposition);assert.deepEqual(raw,input.find(q=>q.bio===5&&q.source_sequence===31));
pass("Complete BIO 5 Q31 quarantine source recoverable",true);
pass("Quarantine excluded from database",ok(await admin.from("questions").select("id").eq("id",identity(sourceIdentity(raw)))).length===0);
pass("One canonical Biochemistry subject",ok(await admin.from("subjects").select("id").or("slug.eq.biochemistry,name.ilike.Biochemistry")).length===1);
const chapters=ok(await admin.from("chapters").select("id,name").eq("subject_id",manifest.taxonomy.subject.id));
pass("Exactly eight canonical BIO chapters",chapters.length===8);
pass("No invented topics or program-specific source scope",rows.every(q=>q.topic_id===null&&q.program_id===null));
pass("All source media remains empty",rows.every(q=>q.question_media.length===0));
pass("No duplicate source identities",new Set(manifest.records.map(q=>q.source_identity)).size===714);
const totals=await query(`select (select count(*) from public.questions) questions,(select count(*) from public.question_options) options,(select count(*) from public.question_answer_keys) keys,(select count(*) from public.question_media) media,(select count(*) from public.question_options o left join public.questions q on q.id=o.question_id where q.id is null) orphan_options,(select count(*) from public.question_answer_keys k left join public.questions q on q.id=k.question_id left join public.question_options o on o.id=k.option_id where q.id is null or o.id is null or o.question_id<>k.question_id) orphan_keys`);
pass("Global orphan options and keys zero",totals[0].orphan_options===0&&totals[0].orphan_keys===0);
const before=read(".local-qa/biochemistry-before.json");
assert.deepEqual(await query(before.sql),before.protected);pass("Pathology/Microbiology complete persisted content hashes unchanged",true);
const tables=rows.flatMap(q=>[q.prompt_rich,q.explanation_rich]).flatMap(d=>d.blocks).filter(b=>b.type==="table");
pass("All eight native tables persisted",tables.length===8);
const last=manifest.runs.at(-1);pass("Complete second run created zero objects",manifest.runs.length>=2&&["new_subjects","new_chapters","new_questions","new_options","new_answer_keys","new_tables","new_import_identities","uploads"].every(k=>last[k]===0)&&last.unchanged_questions===713);
const reconciliation=manifest.taxonomy.chapters.map((c,i)=>({bio:i+1,source:input.filter(q=>q.bio===i+1).length,active:rows.filter(q=>q.chapter_id===c.id&&q.status==="active").length,draft:rows.filter(q=>q.chapter_id===c.id&&q.status==="draft").length,quarantine:quarantine.filter(q=>q.bio===i+1).length,tables:input.filter(q=>q.bio===i+1).reduce((n,q)=>n+q.native_tables,0)}));
writeFileSync("docs/biochemistry-db-verification.json",JSON.stringify({qa_project:manifest.qa_project,checks,reconciliation,totals:totals[0],second_run:last,protected_hashes:before.protected},null,2)+"\n");
writeFileSync(".local-qa/biochemistry-persisted.json",JSON.stringify(rows,null,2));
console.log(JSON.stringify({checks:checks.length,reconciliation,totals:totals[0],second_run:last}));
