import {beforeEach,describe,it,expect,vi} from "vitest";
const mock=vi.hoisted(()=>({getUser:vi.fn(),single:vi.fn(),upload:vi.fn(),remove:vi.fn(),createSignedUrl:vi.fn(),rpc:vi.fn()}));
vi.mock("@/lib/supabase/server",()=>({createClient:async()=>({auth:{getUser:mock.getUser},from:()=>({select:()=>({eq:()=>({single:mock.single})})}),storage:{from:()=>mock},rpc:mock.rpc})}));
import {PATCH} from "./route";
const id="04279d4b-00f4-4bd1-b177-d5d7905f8d6b";
function request(change?: (body:FormData)=>void,origin="https://alslearning.vercel.app") {const body=new FormData();body.set("full_name"," Student Name ");body.set("phone","+971 50 123 4567");change?.(body);return new Request("https://alslearning.vercel.app/api/account/profile",{method:"PATCH",headers:{origin,host:"alslearning.vercel.app"},body})}
describe("Student personal profile endpoint",()=>{
  beforeEach(()=>{vi.resetAllMocks();mock.getUser.mockResolvedValue({data:{user:{id}},error:null});mock.single.mockResolvedValue({data:{role:"student",is_active:true},error:null});mock.upload.mockResolvedValue({error:null});mock.remove.mockResolvedValue({error:null});mock.createSignedUrl.mockResolvedValue({data:{signedUrl:"https://private-photo.example"},error:null});mock.rpc.mockResolvedValue({data:{id,full_name:"Student Name",phone:"+971 50 123 4567",avatar_path:null,previous_avatar_path:null},error:null})});
  it("requires verified active Student authentication",async()=>{mock.getUser.mockResolvedValue({data:{user:null},error:null});expect((await PATCH(request())).status).toBe(401);expect(mock.rpc).not.toHaveBeenCalled();mock.getUser.mockResolvedValue({data:{user:{id}},error:null});mock.single.mockResolvedValue({data:{role:"student",is_active:false},error:null});expect((await PATCH(request())).status).toBe(403)});
  it.each(["email","role","id","program_id","avatar_path"])("rejects protected field %s",async field=>{expect((await PATCH(request(body=>body.set(field,"unauthorized")))).status).toBe(400);expect(mock.rpc).not.toHaveBeenCalled()});
  it("rejects duplicate names and cross-origin writes",async()=>{expect((await PATCH(request(body=>body.append("full_name","Another")))).status).toBe(400);expect((await PATCH(request(undefined,"https://other.example"))).status).toBe(403)});
  it("saves only personal fields with current session identity",async()=>{const response=await PATCH(request());expect(response.status).toBe(200);expect(mock.rpc).toHaveBeenCalledWith("save_student_profile",{target_name:"Student Name",target_phone:"+971 50 123 4567",target_avatar:null});expect(response.headers.get("cache-control")).toBe("private, no-store")});
  it("rejects disguised and oversized images",async()=>{for(const file of [new File(["<svg>"],"photo.png",{type:"image/png"}),new File([new Uint8Array(2097153)],"photo.jpg",{type:"image/jpeg"})]){expect((await PATCH(request(body=>body.set("photo",file)))).status).toBe(400)}expect(mock.upload).not.toHaveBeenCalled()});
  it("removes a new upload after a failed save and preserves the old photo",async()=>{mock.rpc.mockResolvedValue({data:null,error:{message:"denied"}});const response=await PATCH(request(body=>body.set("photo",new File([new Uint8Array([255,216,255])],"photo.jpg",{type:"image/jpeg"}))));expect(response.status).toBe(503);const path=mock.upload.mock.calls[0][0];expect(path).toMatch(new RegExp(`^${id}/.+\\.jpg$`));expect(mock.remove).toHaveBeenCalledExactlyOnceWith([path])});
  it("replaces only the previous photo owned by this Student after commit",async()=>{const previous=`${id}/previous.jpg`;mock.rpc.mockImplementation(async(_name,args)=>({data:{id,full_name:"Student Name",phone:"",avatar_path:args.target_avatar,previous_avatar_path:previous},error:null}));expect((await PATCH(request(body=>body.set("photo",new File([new Uint8Array([255,216,255])],"photo.jpg",{type:"image/jpeg"}))))).status).toBe(200);expect(mock.remove).toHaveBeenCalledWith([previous]);expect(mock.createSignedUrl).toHaveBeenCalled()});
});
